# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'indexekYdao.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtQuickWidgets import QQuickWidget
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QGraphicsView,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QScrollArea, QScrollBar, QSizePolicy, QTabWidget,
    QTextEdit, QToolButton, QTreeView, QTreeWidget,
    QTreeWidgetItem, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(776, 553)
        self.widget = QWidget(Dialog)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 10, 761, 561))
        self.Generate = QTabWidget(self.widget)
        self.Generate.setObjectName(u"Generate")
        self.Generate.setGeometry(QRect(0, 10, 761, 531))
        self.tab_generate = QWidget()
        self.tab_generate.setObjectName(u"tab_generate")
        self.widget_2 = QWidget(self.tab_generate)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(170, 0, 581, 451))
        self.scrollArea = QScrollArea(self.widget_2)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(410, 10, 161, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 159, 429))
        self.scrollArea_3 = QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(10, 10, 141, 411))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 139, 409))
        self.original_view_scroll = QScrollBar(self.scrollAreaWidgetContents_4)
        self.original_view_scroll.setObjectName(u"original_view_scroll")
        self.original_view_scroll.setGeometry(QRect(120, 0, 21, 411))
        self.original_view_scroll.setOrientation(Qt.Vertical)
        self.label_2 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 121, 411))
        self.label_2.setPixmap(QPixmap(u"image.png"))
        self.label_2.setScaledContents(True)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView = QGraphicsView(self.widget_2)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 10, 391, 431))
        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 20, 321, 411))
        self.label.setPixmap(QPixmap(u"manual.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.open_in_editor_button = QPushButton(self.tab_generate)
        self.open_in_editor_button.setObjectName(u"open_in_editor_button")
        self.open_in_editor_button.setGeometry(QRect(640, 450, 101, 41))
        self.treeView_generated = QTreeView(self.tab_generate)
        self.treeView_generated.setObjectName(u"treeView_generated")
        self.treeView_generated.setGeometry(QRect(10, 10, 151, 431))
        self.treeWidget = QTreeWidget(self.tab_generate)
        QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(self.treeWidget)
        __qtreewidgetitem = QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(self.treeWidget)
        __qtreewidgetitem1 = QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(__qtreewidgetitem1)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(20, 20, 131, 411))
        self.generate_button = QPushButton(self.tab_generate)
        self.generate_button.setObjectName(u"generate_button")
        self.generate_button.setGeometry(QRect(20, 450, 121, 41))
        self.Generate.addTab(self.tab_generate, "")
        self.tab_modify = QWidget()
        self.tab_modify.setObjectName(u"tab_modify")
        self.widget_3 = QWidget(self.tab_modify)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(170, 10, 581, 451))
        self.scrollArea_2 = QScrollArea(self.widget_3)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(410, 0, 161, 441))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 159, 439))
        self.original_view_scroll_2 = QScrollBar(self.scrollAreaWidgetContents_2)
        self.original_view_scroll_2.setObjectName(u"original_view_scroll_2")
        self.original_view_scroll_2.setGeometry(QRect(130, 10, 20, 421))
        self.original_view_scroll_2.setOrientation(Qt.Vertical)
        self.treeView_original_2 = QTreeView(self.scrollAreaWidgetContents_2)
        self.treeView_original_2.setObjectName(u"treeView_original_2")
        self.treeView_original_2.setGeometry(QRect(10, 10, 121, 381))
        self.lineEdit = QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 400, 121, 22))
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setClearButtonEnabled(True)
        self.label_3 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 121, 381))
        self.label_3.setPixmap(QPixmap(u"image.png"))
        self.label_3.setScaledContents(True)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.quickWidget = QQuickWidget(self.widget_3)
        self.quickWidget.setObjectName(u"quickWidget")
        self.quickWidget.setGeometry(QRect(0, 0, 401, 451))
        self.quickWidget.setMouseTracking(False)
        self.quickWidget.setAcceptDrops(False)
        self.quickWidget.setResizeMode(QQuickWidget.SizeRootObjectToView)
        self.tabWidget = QTabWidget(self.tab_modify)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 151, 441))
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.textEdit = QTextEdit(self.tab_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 170, 141, 201))
        self.scrollArea_5 = QScrollArea(self.tab_2)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(0, 0, 141, 161))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setObjectName(u"scrollAreaWidgetContents_6")
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 139, 159))
        self.verticalScrollBar_2 = QScrollBar(self.scrollAreaWidgetContents_6)
        self.verticalScrollBar_2.setObjectName(u"verticalScrollBar_2")
        self.verticalScrollBar_2.setGeometry(QRect(120, 0, 16, 211))
        self.verticalScrollBar_2.setOrientation(Qt.Vertical)
        self.checkBox_4 = QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(10, 10, 91, 21))
        self.checkBox_5 = QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(10, 40, 91, 21))
        self.checkBox_5.setTristate(False)
        self.checkBox_6 = QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 70, 91, 21))
        self.checkBox_7 = QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 100, 91, 21))
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.pushButton_2 = QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 380, 71, 24))
        self.pushButton_5 = QPushButton(self.tab_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(70, 380, 71, 24))
        self.tabWidget.addTab(self.tab_2, "")
        self.generate_button_2 = QPushButton(self.tab_modify)
        self.generate_button_2.setObjectName(u"generate_button_2")
        self.generate_button_2.setGeometry(QRect(20, 450, 121, 41))
        self.label_5 = QLabel(self.tab_modify)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(470, 470, 281, 20))
        font = QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.Generate.addTab(self.tab_modify, "")
        self.tab_save = QWidget()
        self.tab_save.setObjectName(u"tab_save")
        self.save_cancel = QPushButton(self.tab_save)
        self.save_cancel.setObjectName(u"save_cancel")
        self.save_cancel.setGeometry(QRect(650, 460, 101, 31))
        self.widget_4 = QWidget(self.tab_save)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(0, 0, 401, 451))
        self.graphicsView_2 = QGraphicsView(self.widget_4)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(10, 10, 391, 431))
        self.label_4 = QLabel(self.widget_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 20, 321, 411))
        self.label_4.setPixmap(QPixmap(u"manual.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.textEditSaveInfo = QTextEdit(self.tab_save)
        self.textEditSaveInfo.setObjectName(u"textEditSaveInfo")
        self.textEditSaveInfo.setGeometry(QRect(410, 10, 341, 381))
        self.textEditSaveInfo.setReadOnly(True)
        self.save_save = QPushButton(self.tab_save)
        self.save_save.setObjectName(u"save_save")
        self.save_save.setGeometry(QRect(540, 460, 101, 31))
        self.openFolder = QToolButton(self.tab_save)
        self.openFolder.setObjectName(u"openFolder")
        self.openFolder.setGeometry(QRect(730, 400, 21, 41))
        self.lineEdit_2 = QLineEdit(self.tab_save)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(410, 400, 321, 41))
        self.Generate.addTab(self.tab_save, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.textEdit_2 = QTextEdit(self.tab)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(140, 10, 611, 481))
        self.pushButton = QPushButton(self.tab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 100, 121, 31))
        self.pushButton_3 = QPushButton(self.tab)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 20, 121, 31))
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 60, 121, 31))
        self.Generate.addTab(self.tab, "")
        self.feedback_button = QPushButton(self.widget)
        self.feedback_button.setObjectName(u"feedback_button")
        self.feedback_button.setGeometry(QRect(660, 0, 81, 24))

        self.retranslateUi(Dialog)

        self.Generate.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_2.setText("")
        self.label.setText("")
        self.open_in_editor_button.setText(QCoreApplication.translate("Dialog", u"open in editor", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Dialog", u"mechanic_parts", None));

        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.treeWidget.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("Dialog", u"YBB100", None));
        ___qtreewidgetitem2 = self.treeWidget.topLevelItem(1)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("Dialog", u"YBB200", None));
        ___qtreewidgetitem3 = self.treeWidget.topLevelItem(2)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("Dialog", u"YBB200-124", None));
        ___qtreewidgetitem4 = ___qtreewidgetitem3.child(0)
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("Dialog", u"YBB202", None));
        ___qtreewidgetitem5 = ___qtreewidgetitem3.child(1)
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("Dialog", u"YBB203", None));
        ___qtreewidgetitem6 = self.treeWidget.topLevelItem(3)
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("Dialog", u"YBB133", None));
        ___qtreewidgetitem7 = self.treeWidget.topLevelItem(4)
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("Dialog", u"YYB114", None));
        ___qtreewidgetitem8 = self.treeWidget.topLevelItem(5)
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("Dialog", u"YYB1919", None));
        ___qtreewidgetitem9 = ___qtreewidgetitem8.child(0)
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("Dialog", u"YBB1919-114514", None));
        self.treeWidget.setSortingEnabled(__sortingEnabled)

        self.generate_button.setText(QCoreApplication.translate("Dialog", u"Generate", None))
        self.Generate.setTabText(self.Generate.indexOf(self.tab_generate), QCoreApplication.translate("Dialog", u"Generate", None))
#if QT_CONFIG(whatsthis)
        self.lineEdit.setWhatsThis(QCoreApplication.translate("Dialog", u"Search", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"Search", None))
        self.label_3.setText("")
        self.checkBox_4.setText(QCoreApplication.translate("Dialog", u"Part1", None))
        self.checkBox_5.setText(QCoreApplication.translate("Dialog", u"Part2", None))
        self.checkBox_6.setText(QCoreApplication.translate("Dialog", u"Part3", None))
        self.checkBox_7.setText(QCoreApplication.translate("Dialog", u"Part4", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"save", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"preview", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Annotation", None))
        self.generate_button_2.setText(QCoreApplication.translate("Dialog", u"Generate", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"*hint: 'wsad' and mouse to move and zoom the view", None))
        self.Generate.setTabText(self.Generate.indexOf(self.tab_modify), QCoreApplication.translate("Dialog", u"Editor", None))
        self.save_cancel.setText(QCoreApplication.translate("Dialog", u"cancel", None))
        self.label_4.setText("")
        self.textEditSaveInfo.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ID: 1<br />Size: 348KB<br />Pages: 1<br />Container: PDF<br />Format profile: High@L4<br />Page size: 21.587 x 27.937<br />Color space: YUV<br />Stream size: 4.34 GiB (97%)<br />Writing library: core 157 r2969 d4099dd<br /><br />Author information:<br />Date: dd/mm/yyyy<br />Security: None<br />Read only: No<br /></p></body></html>", None))
        self.save_save.setText(QCoreApplication.translate("Dialog", u"save", None))
        self.openFolder.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("Dialog", u"default C:/system/Appdata/Roam/CADM/doc", None))
        self.Generate.setTabText(self.Generate.indexOf(self.tab_save), QCoreApplication.translate("Dialog", u"Save", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Save as PDF", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Update Annotation", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"Add Image", None))
        self.Generate.setTabText(self.Generate.indexOf(self.tab), QCoreApplication.translate("Dialog", u"ViewManual", None))
        self.feedback_button.setText(QCoreApplication.translate("Dialog", u"Feedback", None))
    # retranslateUi

